services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    expose:
      - "5432"
    volumes:
      - db:/var/lib/postgresql/data
    env_file: ".env"
volumes:
  db:
    driver: local
