services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data
      - ./src/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

volumes:
  db:
    driver: local
